# Generated by Django 4.2 on 2024-04-13 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_remove_donation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
